version: '3.8'
services:
    db:
        image: jbergstroem/mariadb-alpine
        volumes:
            - ./db:/var/lib/mysql:cached
            - /etc/localtime:/etc/localtime
        env_file: 
            - env/.env
            - env/db.env
        restart: always
    theia:
        image: theiaide/theia-https:latest
        volumes:
            - .:/home/project:cached
            - /etc/localtime:/etc/localtime
        ports:
            - 25579:10443
        env_file: 
            - env/.env
            - env/theia.env
        restart: always
    bungeecord:
        image: adoptopenjdk/openjdk11:alpine-jre
        ports:
            - ${PORT_MINECRAFT}:${PORT_MINECRAFT}
        entrypoint:
            - java
            - -Xms1G
            - -Xmx1G
            - -jar
            - ${JAR_BC}
            - nogui
        volumes:
            - './${DIR_BUNGEECORD}:/worker:cached'
        env_file: 
            - env/.env
        working_dir: /worker
        restart: unless-stopped
    minecraft:
        image: adoptopenjdk/openjdk11:alpine-jre
        ports:
            - ${PORT_RCON}:${PORT_RCON}
        entrypoint:
            - java
            - -Xms1G
            - -Xmx1G
            - -XX:+TieredCompilation
            - -XX:TieredStopAtLevel=1
            - -XX:+UseG1GC
            - -XX:+ParallelRefProcEnabled
            - -XX:MaxGCPauseMillis=200
            - -XX:+UnlockExperimentalVMOptions
            - -XX:+DisableExplicitGC
            - -XX:+AlwaysPreTouch
            - -XX:G1NewSizePercent=30
            - -XX:G1MaxNewSizePercent=40
            - -XX:G1HeapRegionSize=8M
            - -XX:G1ReservePercent=20
            - -XX:G1HeapWastePercent=5
            - -XX:G1MixedGCCountTarget=4
            - -XX:InitiatingHeapOccupancyPercent=15
            - -XX:G1MixedGCLiveThresholdPercent=90
            - -XX:G1RSetUpdatingPauseTimePercent=5
            - -XX:SurvivorRatio=32
            - -XX:+PerfDisableSharedMem
            - -XX:MaxTenuringThreshold=1
            - -Dusing.aikars.flags=https://mcflags.emc.gs
            - -Daikars.new.flags=true
            - -jar
            - ${JAR_MC}
            - nogui
        volumes:
            - './${DIR_MCSERVER}:/worker:cached'
        env_file: 
            - env/.env
        depends_on:
            - bungeecord
            - db
        working_dir: /worker
        restart: unless-stopped
